### ISSUE TITLE
Move to ZNES Repository?

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/HESYSOPT#4]
I would like to build on top of HESYSOPT and add my own classes, etc.

Would it be an option to move it to the ZNES repo?

Otherwise I would probably just fork it and move it there.

**Comment by simnh** [comment]
If it makes you happy ;) ... If we do so, I think it would be great to work for a release. So that you do not only work on a feature branch, but that we try to build a better application...

**Comment by simnh** [comment]
shall i move it?

**Comment by ckaldemeyer** [comment]
> If it makes you happy ;) ... If we do so, I think it would be great to work for a release. So that you do not only work on a feature branch, but that we try to build a better application...

I just want to use/extend oemof for heat modelling in our project and think that your work is a really good starter. But if I would put quite some effort in it (new classes, documentation, streamlining, ...) and maybe other people want to contribute in any form, it becomes more and more a common product. So I think the ZNES repo would be much more suitable..

But if you want to "keep it as your baby" it is also o.k. for me. I would then just take some approaches and start my own project there. It's more about what makes you happy/unhappy ;)

> shall i move it?

See above.

**Comment by simnh** [comment]
No its great...of course it will get a common/shared project. I am just interested in working on it two so we can use synergies and make it a good 'product'... I will move it...I think you do not need to change anything as github will take care of everything...

**Comment by simnh** [comment]
we are here ;) , you might want to:

git remote set-url origin new_url

**Comment by ckaldemeyer** [comment]
Works! Thanks
